### ISSUE TITLE
SMSR switch build broken

### ISSUE THREAD

**Issue by catfromplan9** [PeachyPeachSM64/sm64ex-omm-romhacks#2]
See https://github.com/PeachyPeachSM64/sm64ex-omm-romhacks/pull/3

**Comment by catfromplan9** [comment]
Actually, I'll PR this

**Comment by catfromplan9** [comment]
https://github.com/PeachyPeachSM64/sm64ex-omm-romhacks/pull/3

**Comment by PeachyPeachSM64** [comment]
thanks for fixing the switch build
