### ISSUE TITLE
SMGS lacks switch build

### ISSUE THREAD

**Issue by catfromplan9** [PeachyPeachSM64/sm64ex-omm-romhacks#4]
Please update SMGS to support building for the switch, thank you

**Comment by PeachyPeachSM64** [comment]
sadly the Green Stars port is based on a fork of [sm64ex-nightly](https://github.com/sm64pc/sm64ex/tree/nightly), which doesn't have non-PC builds

**Comment by catfromplan9** [comment]
> sadly the Green Stars port is based on a fork of [sm64ex-nightly](https://github.com/sm64pc/sm64ex/tree/nightly), which doesn't have non-PC builds

Is there a way to rebase it to sm64ex codebase? I want to try doing this, as well as with another romhack. Also, how are these ports created? Is it a recreation of the romhack or is there some procedure I could follow to go about making my own ports? I want to try porting some romhacks to sm64ex for use on my modded switch, because N64 emulation is not nearly as comfortable as native ports

**Comment by PeachyPeachSM64** [comment]
I don't know if it still works with the latest ex-alo, but you can convert old ROM-hacks and ROM Manager hacks into PC port compliant files, using [ROM Manager 2 C](https://github.com/AloXado320/rom-manager-2-c)
